### ISSUE TITLE
Allow passing directory as argument to image-tile-viewer.open command

### ISSUE THREAD

**Issue by i-ky** [ayatough/vscode-image-tile-viewer#21]
First of all, thank you for this extension! I find it very useful.

Application that I work on, dumps images to a specific directory. I would like to add a task that would open this directory without me typing the path every time:
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "View images from my special directory",
            "type": "shell",
            "command": "echo ${input:OpenSpecialDir}"
        }
    ],
    "inputs": [
        {
            "id": "OpenSpecialDir",
            "type": "command",
            "command": "image-tile-viewer.open",
            "args": [ "/path/to/my/special/directory" ]
        }
    ]
}
```
Then I would press `Ctrl + P` and type `task View images from...`. As of now this opens directory selection. Please add a possibility for `image-tile-viewer.open` to get directory from arguments.

**Comment by ayatough** [comment]
Thank you for nice suggestion!
This feature is added v0.2.2.
